[package]
name = "render-core"
edition.workspace = true
version.workspace = true

[dependencies]
render-ir.workspace = true
base64 = "0.22"
percent-encoding = "2"
blitz-dom = "0.2.4"
blitz-html = "0.2.0"
blitz-traits = "0.2"
parley = "0.6"
style = { package = "stylo", version = "0.8" }
slab = "0.4"
